-- 수시 위험성평가의 유해·위험요인 참조 DB(위험요인 + 감소대책)와 분류 캐스케이드 뷰를 만드는 마이그레이션

-- =============================================================================
-- 개요
--   원본: C:\Users\EKR\Desktop\위험성평가\자체 유해·위험요인 DB.xlsx
--         시트 "위험요인 도출표(최종)" 62,316 데이터 행
--   적재: 위험요인 18,259건 + 감소대책 62,316건 (safesys-app/scripts/import-risk-hazards.js)
--   성격: 전사 공통 참조 데이터. 프로젝트 종속이 아니므로 project_id 없음.
--         쓰기는 임포트 스크립트(service role)만 수행하고 앱은 읽기만 한다.
--   재실행 안전: IF NOT EXISTS / OR REPLACE / DROP POLICY IF EXISTS 사용
--   Supabase 콘솔에서 수동 적용.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. 위험요인 테이블
--    id는 임포트 스크립트가 감소대책 연결용으로 직접 부여하므로 BY DEFAULT 식별자
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.risk_hazards (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_type TEXT NOT NULL,
  construction TEXT NOT NULL,
  unit_work TEXT NOT NULL,
  detail_work TEXT NOT NULL,
  hazard TEXT NOT NULL,
  disaster_type TEXT NOT NULL DEFAULT '',
  related_law TEXT NOT NULL DEFAULT '',
  work_permit TEXT NOT NULL DEFAULT '',
  flag_serious BOOLEAN NOT NULL DEFAULT FALSE,
  flag_accident_case BOOLEAN NOT NULL DEFAULT FALSE,
  flag_near_miss BOOLEAN NOT NULL DEFAULT FALSE,
  flag_sif BOOLEAN NOT NULL DEFAULT FALSE,
  flag_profile BOOLEAN NOT NULL DEFAULT FALSE
);

-- 캐스케이드 선택(사업별→공사→단위작업→세부단위작업)과 세부단위작업별 위험요인 조회를 함께 받는 인덱스
CREATE INDEX IF NOT EXISTS idx_risk_hazards_taxonomy
  ON public.risk_hazards(business_type, construction, unit_work, detail_work);

-- 사업별 무관(전체) 모드에서 공사·단위작업·세부단위작업만으로 조회하는 경로
CREATE INDEX IF NOT EXISTS idx_risk_hazards_work
  ON public.risk_hazards(construction, unit_work, detail_work);

COMMENT ON TABLE public.risk_hazards IS
  '한국농어촌공사 자체 유해·위험요인 DB의 위험요인 원문. 사업별>공사>단위작업>세부단위작업 4단계 분류로 조회한다';
COMMENT ON COLUMN public.risk_hazards.related_law IS
  '관계법령. 원본은 감소대책 행마다 인용 법령이 달라 위험요인 단위로 중복 제거 후 " / "로 이어 붙였다';
COMMENT ON COLUMN public.risk_hazards.flag_sif IS
  'SIF(중상해·사망 유발 가능) 표시. 공사중대재해 표시와 함께 강도 상향 판단 근거로 쓴다';

-- -----------------------------------------------------------------------------
-- 2. 감소대책 테이블 (위험요인 1건당 1~7건)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.risk_hazard_measures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hazard_id INTEGER NOT NULL REFERENCES public.risk_hazards(id) ON DELETE CASCADE,
  measure TEXT NOT NULL,
  sort_order SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_risk_hazard_measures_hazard
  ON public.risk_hazard_measures(hazard_id, sort_order);

COMMENT ON TABLE public.risk_hazard_measures IS
  '위험요인별 감소대책 원문. 원본 엑셀에서 No.가 "-"인 연속 행이 같은 위험요인의 추가 대책이다';

-- -----------------------------------------------------------------------------
-- 3. 분류 캐스케이드 뷰 (유효 조합 2,592개)
--    위험요인 18,259행을 매번 훑지 않고 다음 단계 목록만 뽑기 위한 축약 뷰
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.risk_hazard_taxonomy
WITH (security_invoker = on) AS
SELECT DISTINCT business_type, construction, unit_work, detail_work
  FROM public.risk_hazards;

COMMENT ON VIEW public.risk_hazard_taxonomy IS
  '위험요인 분류 4단계의 유효 조합. GET /api/risk-db/taxonomy 의 캐스케이드 옵션 조회용';

GRANT SELECT ON public.risk_hazard_taxonomy TO authenticated;

-- -----------------------------------------------------------------------------
-- 4. RLS — 전사 공통 참조 데이터이므로 로그인 사용자 읽기 전용, 쓰기는 service role만
-- -----------------------------------------------------------------------------
ALTER TABLE public.risk_hazards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_hazard_measures ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "로그인 사용자 위험요인 조회" ON public.risk_hazards;
CREATE POLICY "로그인 사용자 위험요인 조회"
  ON public.risk_hazards FOR SELECT TO authenticated
  USING (TRUE);

DROP POLICY IF EXISTS "로그인 사용자 감소대책 조회" ON public.risk_hazard_measures;
CREATE POLICY "로그인 사용자 감소대책 조회"
  ON public.risk_hazard_measures FOR SELECT TO authenticated
  USING (TRUE);
